using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace TEC.ORM.Mapping.Generator;

/// <summary>
/// Gera o código de um DTO: projeção (<c>Expression</c>, traduzível pelo EF Core), conversão em memória, <c>ApplyTo</c>,
/// <c>ToEntity</c> e extensões. DTOs aninhados são expandidos em linha (a projeção precisa ser uma única expressão).
/// </summary>
internal sealed class MappingEmitter
{
    /// <summary>Limite de segurança de aninhamento (além de MaxDepth).</summary>
    private const int MaxNesting = 32;

    private static readonly SymbolDisplayFormat Fq = SymbolDisplayFormat.FullyQualifiedFormat;

    private readonly DtoAnalyzer _analyzer;
    private readonly DtoModel _root;
    private int _variable;

    public MappingEmitter(DtoAnalyzer analyzer, DtoModel root)
    {
        _analyzer = analyzer;
        _root = root;
    }

    /// <summary>Erro encontrado na expansão (ciclo sem MaxDepth); impede a geração.</summary>
    public DiagnosticInfo? Error { get; private set; }

    private sealed class Frame
    {
        public Frame(INamedTypeSymbol dto, string? edge, int maxDepth)
        {
            Dto = dto;
            Edge = edge;
            MaxDepth = maxDepth;
        }

        public INamedTypeSymbol Dto { get; }

        public string? Edge { get; }

        public int MaxDepth { get; }
    }

    public string? Emit()
    {
        var dto = _root.Dto;
        var entity = _root.Entity!;
        string dtoType = dto.ToDisplayString(Fq);
        string entityType = entity.ToDisplayString(Fq);

        _variable = 0;
        string projection = NewDto(_root, "s0", [new Frame(dto, null, 0)], forExpression: true);
        if (Error is not null)
            return null;
        _variable = 0;
        string inMemory = NewDto(_root, "s0", [new Frame(dto, null, 0)], forExpression: false);
        if (Error is not null)
            return null;

        bool hasReverse = _root.Properties.Any(p => p.Reverse != ReverseConversion.None);
        // DTO público com entidade não pública: membros públicos com o tipo da entidade não compilariam (CS0050/CS0051).
        // Nesse caso os membros gerados ficam internal e as interfaces são implementadas explicitamente.
        bool restricted = dto.DeclaredAccessibility == Accessibility.Public && !IsEffectivelyPublic(entity);
        string access = restricted ? "internal" : "public";
        string accessibility = dto.DeclaredAccessibility == Accessibility.Public && !restricted ? "public" : "internal";

        var code = new StringBuilder();
        code.AppendLine("// <auto-generated/>");
        code.AppendLine($"// Gerado pelo TEC.ORM.Mapping a partir de [MapFrom(typeof({entity.Name}))] em {dto.Name}. Não edite.");
        code.AppendLine("#nullable enable");
        code.AppendLine("#pragma warning disable");
        code.AppendLine();
        bool hasNamespace = !dto.ContainingNamespace.IsGlobalNamespace;
        string indent = hasNamespace ? "    " : "";
        if (hasNamespace)
        {
            code.AppendLine($"namespace {dto.ContainingNamespace.ToDisplayString(Fq).Substring("global::".Length)}");
            code.AppendLine("{");
        }

        string interfaces = $"global::TEC.ORM.Mapping.IDtoMap<{entityType}, {dtoType}>, global::TEC.ORM.Mapping.IDtoReverseMap<{entityType}>";
        if (_root.CanCreateEntity)
            interfaces += $", global::TEC.ORM.Mapping.IDtoEntityFactory<{entityType}>";

        string kind = dto.IsRecord ? "record" : "class";
        code.AppendLine($"{indent}[global::System.CodeDom.Compiler.GeneratedCode(\"TEC.ORM.Mapping\", \"0.0.1\")]");
        code.AppendLine($"{indent}partial {kind} {Id(dto.Name)} : {interfaces}");
        code.AppendLine($"{indent}{{");
        string member = indent + "    ";
        string body = member + "    ";

        // Conversores: um por propriedade, em campo estático (internal: usados também por DTOs que expandem este em linha)
        foreach (var property in _root.Properties.Where(p => p.Converter is not null))
            code.AppendLine($"{member}internal static readonly {property.Converter!.ToDisplayString(Fq)} {property.ConverterFieldName} = new {property.Converter!.ToDisplayString(Fq)}();");

        string expressionType = $"global::System.Linq.Expressions.Expression<global::System.Func<{entityType}, {dtoType}>>";
        code.AppendLine($"{member}private static readonly {expressionType} __TecOrmProjection = s0 => {projection};");
        code.AppendLine();
        code.AppendLine($"{member}/// <summary>Projeção para consultas: SELECT só das colunas usadas por este DTO, com os aninhados.</summary>");
        code.AppendLine($"{member}{access} static {expressionType} Projection => __TecOrmProjection;");
        code.AppendLine();
        code.AppendLine($"{member}/// <summary>Converte uma entidade carregada em memória.</summary>");
        code.AppendLine($"{member}{access} static {dtoType} FromEntity({entityType} entity)");
        code.AppendLine($"{member}{{");
        code.AppendLine($"{body}if (entity == null) throw new global::System.ArgumentNullException(nameof(entity));");
        code.AppendLine($"{body}var s0 = entity;");
        code.AppendLine($"{body}return {inMemory};");
        code.AppendLine($"{member}}}");
        code.AppendLine();

        code.AppendLine($"{member}/// <summary>Copia os valores deste DTO sobre a entidade (sem Id, exclusão lógica, achatados e somente leitura).</summary>");
        code.AppendLine($"{member}{access} void ApplyTo({entityType} entity)");
        code.AppendLine($"{member}{{");
        code.AppendLine($"{body}if (entity == null) throw new global::System.ArgumentNullException(nameof(entity));");
        if (hasReverse)
            code.AppendLine($"{body}__TecOrmApply(entity);");
        code.AppendLine($"{member}}}");

        if (_root.CanCreateEntity)
        {
            code.AppendLine();
            code.AppendLine($"{member}/// <summary>Cria uma entidade nova com os valores deste DTO.</summary>");
            code.AppendLine($"{member}{access} {entityType} ToEntity()");
            code.AppendLine($"{member}{{");
            code.AppendLine($"{body}var entity = new {entityType}();");
            if (hasReverse)
                code.AppendLine($"{body}__TecOrmApply(entity);");
            code.AppendLine($"{body}return entity;");
            code.AppendLine($"{member}}}");
        }

        if (hasReverse)
        {
            code.AppendLine();
            code.AppendLine($"{member}private void __TecOrmApply({entityType} entity)");
            code.AppendLine($"{member}{{");
            int index = 0;
            foreach (var property in _root.Properties.Where(p => p.Reverse != ReverseConversion.None))
                AppendReverse(code, body, property, index++);
            code.AppendLine($"{member}}}");
        }

        if (restricted)
        {
            code.AppendLine();
            code.AppendLine($"{member}// Contratos implementados explicitamente: a entidade não é pública, então os membros acima são internal");
            code.AppendLine($"{member}static {expressionType} global::TEC.ORM.Mapping.IDtoMap<{entityType}, {dtoType}>.Projection => __TecOrmProjection;");
            code.AppendLine($"{member}static {dtoType} global::TEC.ORM.Mapping.IDtoMap<{entityType}, {dtoType}>.FromEntity({entityType} entity) => FromEntity(entity);");
            code.AppendLine($"{member}void global::TEC.ORM.Mapping.IDtoReverseMap<{entityType}>.ApplyTo({entityType} entity) => ApplyTo(entity);");
            if (_root.CanCreateEntity)
                code.AppendLine($"{member}{entityType} global::TEC.ORM.Mapping.IDtoEntityFactory<{entityType}>.ToEntity() => ToEntity();");
        }

        code.AppendLine($"{indent}}}");
        code.AppendLine();

        // Extensões
        string name = dto.Name;
        code.AppendLine($"{indent}/// <summary>Conversões entre <see cref=\"{entityType}\"/> e <see cref=\"{dtoType}\"/> (geradas).</summary>");
        code.AppendLine($"{indent}[global::System.CodeDom.Compiler.GeneratedCode(\"TEC.ORM.Mapping\", \"0.0.1\")]");
        code.AppendLine($"{indent}{accessibility} static partial class {name}MappingExtensions");
        code.AppendLine($"{indent}{{");
        code.AppendLine($"{member}/// <summary>Converte a entidade em <see cref=\"{dtoType}\"/>.</summary>");
        code.AppendLine($"{member}public static {dtoType} To{name}(this {entityType} entity) => {dtoType}.FromEntity(entity);");
        code.AppendLine();
        code.AppendLine($"{member}/// <summary>Converte as entidades em uma lista de <see cref=\"{dtoType}\"/>.</summary>");
        code.AppendLine($"{member}public static global::System.Collections.Generic.List<{dtoType}> To{name}List(this global::System.Collections.Generic.IEnumerable<{entityType}> entities)");
        code.AppendLine($"{member}{{");
        code.AppendLine($"{body}if (entities == null) throw new global::System.ArgumentNullException(nameof(entities));");
        code.AppendLine($"{body}return global::System.Linq.Enumerable.ToList(global::System.Linq.Enumerable.Select(entities, {dtoType}.FromEntity));");
        code.AppendLine($"{member}}}");
        code.AppendLine();
        code.AppendLine($"{member}/// <summary>Projeta a consulta para <see cref=\"{dtoType}\"/> (SELECT só das colunas do DTO).</summary>");
        code.AppendLine($"{member}public static global::System.Linq.IQueryable<{dtoType}> ProjectTo{name}(this global::System.Linq.IQueryable<{entityType}> query) =>");
        code.AppendLine($"{body}global::System.Linq.Queryable.Select(query, {dtoType}.Projection);");
        code.AppendLine($"{indent}}}");

        if (hasNamespace)
            code.AppendLine("}");
        return code.ToString();
    }

    // ---------- Entidade → DTO (expressão única, aninhados em linha) ----------

    private string NewDto(DtoModel model, string source, List<Frame> stack, bool forExpression)
    {
        var assignments = new List<string>();
        foreach (var property in model.Properties.Where(p => p.Forward))
        {
            string? value = property.Kind switch
            {
                PropertyKind.Scalar => Scalar(model, property, source),
                PropertyKind.Object => NestedObject(model, property, source, stack, forExpression),
                _ => NestedList(model, property, source, stack, forExpression)
            };
            if (Error is not null)
                return string.Empty;
            assignments.Add($"{Id(property.Name)} = {value}");
        }
        return $"new {model.Dto.ToDisplayString(Fq)} {{ {string.Join(", ", assignments)} }}";
    }

    /// <summary>Acesso ao caminho e condição de nulo dos segmentos intermediários (referências).</summary>
    private static (string Access, List<string> Guards) Path(PropertyMap property, string source, bool includeLast)
    {
        var guards = new List<string>();
        string access = source;
        for (int i = 0; i < property.Path.Count; i++)
        {
            access += "." + Id(property.Path[i].Name);
            bool last = i == property.Path.Count - 1;
            if ((!last || includeLast) && property.Path[i].Type.IsReferenceType)
                guards.Add($"{access} == null");
        }
        return (access, guards);
    }

    private static string Guarded(List<string> guards, string fallback, string value) =>
        guards.Count == 0 ? value : $"(({string.Join(" || ", guards)}) ? {fallback} : {value})";

    private static string Scalar(DtoModel model, PropertyMap property, string source)
    {
        string target = property.DtoType.ToDisplayString(Fq);
        var (access, guards) = Path(property, source, includeLast: false);
        string value = property.Conversion switch
        {
            ForwardConversion.Identity => access,
            ForwardConversion.ImplicitCast => $"({target})({access})",
            ForwardConversion.NullableToValue => $"({target})(({access}) ?? default({property.NullableUnderlying!.ToDisplayString(Fq)}))",
            ForwardConversion.EnumToString => $"({access}).ToString()",
            ForwardConversion.StringToEnum =>
                $"(({access}) == null ? default({target}) : ({target})global::System.Enum.Parse(typeof({target}), {access}, true))",
            _ => $"{model.Dto.ToDisplayString(Fq)}.{property.ConverterFieldName}.Convert({access})"
        };
        return Guarded(guards, $"default({target})", value);
    }

    private string NestedObject(DtoModel model, PropertyMap property, string source, List<Frame> stack, bool forExpression)
    {
        string target = property.DtoType.WithNullableAnnotation(NullableAnnotation.NotAnnotated).ToDisplayString(Fq);
        var (access, guards) = Path(property, source, includeLast: true);
        var nested = Enter(model, property, stack, out bool cut);
        if (Error is not null)
            return string.Empty;
        if (cut || nested is null)
            return $"default({target})";

        stack.Add(new Frame(nested.Dto, Edge(model, property), property.MaxDepth));
        string value = NewDto(nested, access, stack, forExpression);
        stack.RemoveAt(stack.Count - 1);
        return Guarded(guards, $"default({target})", value);
    }

    private string NestedList(DtoModel model, PropertyMap property, string source, List<Frame> stack, bool forExpression)
    {
        string element = property.DtoElementType!.WithNullableAnnotation(NullableAnnotation.NotAnnotated).ToDisplayString(Fq);
        string empty = property.Shape == CollectionShape.Array
            ? $"new {element}[0]"
            : $"new global::System.Collections.Generic.List<{element}>()";
        string materialize = property.Shape == CollectionShape.Array ? "ToArray" : "ToList";

        // Na expressão, a própria coleção não é comparada a null (navegação de coleção nunca é nula para o ORM)
        var (access, guards) = Path(property, source, includeLast: !forExpression);

        string selected;
        if (property.NestedDto is null)
        {
            string elementVariable = "e" + ++_variable;
            selected = property.ElementCast
                ? $"global::System.Linq.Enumerable.Select({access}, {elementVariable} => ({element}){elementVariable})"
                : access;
        }
        else
        {
            var nested = Enter(model, property, stack, out bool cut);
            if (Error is not null)
                return string.Empty;
            if (cut || nested is null)
                return empty;

            string elementVariable = "e" + ++_variable;
            stack.Add(new Frame(nested.Dto, Edge(model, property), property.MaxDepth));
            string newElement = NewDto(nested, elementVariable, stack, forExpression);
            stack.RemoveAt(stack.Count - 1);
            selected = $"global::System.Linq.Enumerable.Select({access}, {elementVariable} => {newElement})";
        }

        return Guarded(guards, empty, $"global::System.Linq.Enumerable.{materialize}({selected})");
    }

    /// <summary>
    /// Decide se o DTO aninhado é expandido. Em ciclo: corta quando esta propriedade já foi expandida <c>MaxDepth</c> vezes no
    /// caminho; sem MaxDepth, só continua se outra propriedade do mesmo ciclo tiver MaxDepth (que limita a recursão), senão é erro.
    /// </summary>
    private DtoModel? Enter(DtoModel model, PropertyMap property, List<Frame> stack, out bool cut)
    {
        cut = false;
        var nested = _analyzer.Analyze(property.NestedDto!);
        if (!nested.IsValid)
        {
            // O DTO aninhado reporta os próprios erros; este não é gerado
            Error ??= DiagnosticInfo.Create(MappingDiagnostics.NotMappedDto, property.Location, property.Name, nested.Dto.Name,
                "tem erros de mapeamento (veja os erros desse DTO)");
            return null;
        }

        string edge = Edge(model, property);
        if (property.MaxDepth > 0 && stack.Count(f => f.Edge == edge) >= property.MaxDepth)
        {
            cut = true;
            return null;
        }

        int previous = stack.FindLastIndex(f => SymbolEqualityComparer.Default.Equals(f.Dto, nested.Dto));
        if (previous >= 0 && property.MaxDepth == 0 && !stack.Skip(previous + 1).Any(f => f.MaxDepth > 0))
        {
            string cycle = string.Join(" → ", stack.Skip(previous).Select(f => f.Dto.Name).Concat(new[] { nested.Dto.Name }));
            Error = DiagnosticInfo.Create(MappingDiagnostics.Cycle, _root.Location, _root.Dto.Name, cycle);
            return null;
        }

        if (stack.Count >= MaxNesting)
        {
            Error = DiagnosticInfo.Create(MappingDiagnostics.Cycle, _root.Location, _root.Dto.Name,
                $"mais de {MaxNesting} níveis de aninhamento (reduza MaxDepth)");
            return null;
        }
        return nested;
    }

    /// <summary>Identificador seguro no código gerado: palavra-chave reservada ganha '@' (ex.: <c>@class</c>).</summary>
    private static string Id(string name) => SyntaxFacts.GetKeywordKind(name) != SyntaxKind.None ? "@" + name : name;

    /// <summary>O tipo (com os que o contêm e os argumentos genéricos) é público.</summary>
    private static bool IsEffectivelyPublic(ITypeSymbol type)
    {
        for (var current = type; current is not null; current = current.ContainingType)
        {
            if (current.DeclaredAccessibility != Accessibility.Public)
                return false;
            if (current is INamedTypeSymbol { IsGenericType: true } generic && !generic.TypeArguments.All(a => a.TypeKind == TypeKind.TypeParameter || IsEffectivelyPublic(a)))
                return false;
        }
        return true;
    }

    private static string Edge(DtoModel model, PropertyMap property) => model.Dto.ToDisplayString() + "." + property.Name;

    // ---------- DTO → entidade ----------

    private void AppendReverse(StringBuilder code, string indent, PropertyMap property, int index)
    {
        string entityMember = "entity." + Id(property.Path[0].Name);
        string dtoMember = "this." + Id(property.Name);
        string entityType = property.SourceType.ToDisplayString(Fq);

        switch (property.Kind)
        {
            case PropertyKind.Scalar:
                code.AppendLine(indent + property.Reverse switch
                {
                    ReverseConversion.Identity => $"{entityMember} = {dtoMember};",
                    ReverseConversion.ImplicitCast => $"{entityMember} = ({entityType})({dtoMember});",
                    ReverseConversion.NullableKeep => $"if ({dtoMember}.HasValue) {entityMember} = ({entityType}){dtoMember}.Value;",
                    ReverseConversion.StringToEnum =>
                        $"if ({dtoMember} != null && global::System.Enum.TryParse<{entityType}>({dtoMember}, true, out var __value{index}) && " +
                        $"global::System.Enum.IsDefined(typeof({entityType}), __value{index})) {entityMember} = __value{index};",
                    ReverseConversion.EnumToString => $"{entityMember} = {dtoMember}.ToString();",
                    _ => $"{entityMember} = {_root.Dto.ToDisplayString(Fq)}.{property.ConverterFieldName}.ConvertBack({dtoMember});"
                });
                return;

            case PropertyKind.Object:
                code.AppendLine($"{indent}if ({dtoMember} != null)");
                code.AppendLine($"{indent}{{");
                if (property.EntityPropertySettable && _analyzer.Analyze(property.NestedDto!).CanCreateEntity)
                {
                    code.AppendLine($"{indent}    if ({entityMember} == null) {entityMember} = {dtoMember}.ToEntity();");
                    code.AppendLine($"{indent}    else {dtoMember}.ApplyTo({entityMember});");
                }
                else
                    code.AppendLine($"{indent}    if ({entityMember} != null) {dtoMember}.ApplyTo({entityMember});");
                code.AppendLine($"{indent}}}");
                return;

            case PropertyKind.List:
                AppendListSync(code, indent, property, index, entityMember, dtoMember);
                return;
        }
    }

    /// <summary>Sincroniza a coleção pelo Id: atualiza os existentes, cria os novos e remove os ausentes.</summary>
    private void AppendListSync(StringBuilder code, string indent, PropertyMap property, int index, string entityMember, string dtoMember)
    {
        var nested = _analyzer.Analyze(property.NestedDto!);
        string element = nested.Entity!.ToDisplayString(Fq);
        string key = property.SyncKeyType!.ToDisplayString(Fq);
        string collection = $"__collection{index}";
        string existing = $"__existing{index}";
        string seen = $"__seen{index}";
        string i = indent + "    ";
        string ii = i + "    ";

        code.AppendLine($"{indent}if ({dtoMember} != null)");
        code.AppendLine($"{indent}{{");
        code.AppendLine($"{i}global::System.Collections.Generic.ICollection<{element}> {collection} = {entityMember};");
        if (property.EntityPropertySettable)
        {
            code.AppendLine($"{i}if ({collection} == null)");
            code.AppendLine($"{i}{{");
            code.AppendLine($"{ii}var __created{index} = new global::System.Collections.Generic.List<{element}>();");
            code.AppendLine($"{ii}{entityMember} = __created{index};");
            code.AppendLine($"{ii}{collection} = __created{index};");
            code.AppendLine($"{i}}}");
        }
        code.AppendLine($"{i}if ({collection} != null)");
        code.AppendLine($"{i}{{");
        code.AppendLine($"{ii}var {existing} = new global::System.Collections.Generic.Dictionary<{key}, {element}>();");
        code.AppendLine($"{ii}foreach (var __current in {collection}) if (__current != null) {existing}[((global::TEC.ORM.Entities.IEntity<{key}>)__current).Id] = __current;");
        code.AppendLine($"{ii}var {seen} = new global::System.Collections.Generic.HashSet<{key}>();");
        code.AppendLine($"{ii}foreach (var __item in {dtoMember})");
        code.AppendLine($"{ii}{{");
        code.AppendLine($"{ii}    if (__item == null) continue;");
        code.AppendLine($"{ii}    if (!global::System.Collections.Generic.EqualityComparer<{key}>.Default.Equals(__item.Id, default({key})) && {existing}.TryGetValue(__item.Id, out var __match))");
        code.AppendLine($"{ii}    {{");
        code.AppendLine($"{ii}        __item.ApplyTo(__match);");
        code.AppendLine($"{ii}        {seen}.Add(__item.Id);");
        code.AppendLine($"{ii}    }}");
        code.AppendLine($"{ii}    else");
        code.AppendLine($"{ii}        {collection}.Add(__item.ToEntity());   // Id nunca vem do DTO: o banco/ORM gera");
        code.AppendLine($"{ii}}}");
        code.AppendLine($"{ii}foreach (var __pair in {existing}) if (!{seen}.Contains(__pair.Key)) {collection}.Remove(__pair.Value);");
        code.AppendLine($"{i}}}");
        code.AppendLine($"{indent}}}");
    }
}
